version: "2.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=admin
      - DB_NAME=ecare
      - DB_USER=root
      - DB_PASS=root
      - DB_URI=db:3306
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console

  db:
    container_name: "db"
    build:
      context: .
      dockerfile: Dockerfile.data
    command: --disable-partition-engine-check
    ports:
      - "3306:3306"